### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by hjet** [altosaar/nomen#1]

**Comment by hjet** [comment]
@altosaar ping!

**Comment by hjet** [comment]
How is your day going @altosaar? ping!

**Comment by jaanaltosaar** [comment]
i'm sorry

**Comment by hjet** [comment]
> i'm sorry

@altosaar it's ok!

## ping!

- [ ] pls advise
`sys.exit(1)`

**Comment by hjet** [comment]
this was good: http://www.newyorker.com/magazine/2011/10/03/personal-best

**Comment by hjet** [comment]
<img width="917" alt="screen shot 2017-01-12 at 11 42 11 pm" src="https://cloud.githubusercontent.com/assets/3112455/21940329/d310e6a0-d991-11e6-8818-10ab9c8fdcbb.png">
